[registers.mode-control-register]
name = "Mode Control Register"
anchor = "mode-control-register"
bits = 8
description = "Controls MDA video output and text blinking"

[[registers.mode-control-register.register]]
address = "3B8"
access = "Write-Only"

[[registers.mode-control-register.fields]]
name = "HIRES"
lsb = 0
width = 1
description = "**High-Resolution Mode**<br>**0**: Not implemented; must not be set.<br>**1**: High-resolution mode (normal operation)"

[[registers.mode-control-register.fields]]
name = "B/W"
lsb = 1
width = 1
description = "**Black-and-White Mode**<br>Value written is not used."

[[registers.mode-control-register.fields]]
name = "Unused"
lsb = 2
width = 1
description = "Unused"

[[registers.mode-control-register.fields]]
name = "VIDEO"
lsb = 3
width = 1
description = "**Video Enable**<br>**0**: Video output disabled<br>**1**: Video output enabled"

[[registers.mode-control-register.fields]]
name = "Unused"
lsb = 4
width = 1
description = "Unused"

[[registers.mode-control-register.fields]]
name = "BLINK_EN"
lsb = 5
width = 1
description = "**Text Blinking Control**<br>**0**: Attribute bit `7` controls background intensity<br>**1**: Attribute bit `7` controls blinking"

[[registers.mode-control-register.fields]]
name = "Unused"
lsb = 6
width = 2
description = "Unused"

[registers.status-register]
name = "Status Register"
bits = 8
description = "Reports display timing and light-pen status"
register = [{ address = "3DA", access = "Read-Only" }]
fields = [
    { name = "/DE", lsb = 0, width = 1, description = "**Inverted display-enable signal from CRTC.**<br>**0**: CRTC is scanning **inside** the active display area.<br>**1**: CRTC is scanning **outside of** the active display area." },
    { name = "LPT", lsb = 1, width = 1, description = "**Light-pen trigger state**<br>**0**: Light pen trigger has *not* fired<br>**1**: Light pen trigger has fired." },
    { name = "LPS", lsb = 2, width = 1, description = "**Light-pen switch status**<br>**0**: Light pen switch **on**<br>**1**: Light pen switch **off**." },
    { name = "VR", lsb = 3, width = 1, description = "**Vertical retrace status**<br>**0**: VS pin of CRTC is **low**<br>**1**: VS pin of CRTC is **high** (in vertical blank)" },
    { name = "Unused", lsb = 4, width = 4, description = "Unused" },
]
