[registers.mode-control-register]
name = "Mode Control Register"
anchor = "mode-control-register"
bits = 8
description = "Controls MDA video output and text blinking"

[[registers.mode-control-register.register]]
address = "3B8"
access = "Write-Only"

[[registers.mode-control-register.fields]]
name = "HIRES"
lsb = 0
width = 1
description = "**High-Resolution Mode**<br>**0**: Not implemented; must not be set.<br>**1**: High-resolution mode (normal operation)"

[[registers.mode-control-register.fields]]
name = "B/W"
lsb = 1
width = 1
description = "**Black-and-White Mode**<br>Value written is not used."

[[registers.mode-control-register.fields]]
name = "Unused"
lsb = 2
width = 1
description = "Unused"

[[registers.mode-control-register.fields]]
name = "VIDEO"
lsb = 3
width = 1
description = "**Video Enable**<br>**0**: Video output disabled<br>**1**: Video output enabled"

[[registers.mode-control-register.fields]]
name = "Unused"
lsb = 4
width = 1
description = "Unused"

[[registers.mode-control-register.fields]]
name = "BLINK_EN"
lsb = 5
width = 1
description = "**Text Blinking Control**<br>**0**: Attribute bit `7` controls background intensity<br>**1**: Attribute bit `7` controls blinking"

[[registers.mode-control-register.fields]]
name = "Unused"
lsb = 6
width = 2
description = "Unused"

[registers.status-register]
name = "Status Register"
bits = 8
description = "Reports horizontal retrace and current video output status"

[[registers.status-register.register]]
address = "3BA"
access = "Read-Only"

[[registers.status-register.fields]]
name = "RETRACE"
lsb = 0
width = 1
description = "**Horizontal retrace status**<br>**0**: Horizontal retrace is inactive<br>**1**: Horizontal retrace is active"

[[registers.status-register.fields]]
name = "0"
lsb = 1
width = 1
color = "EEEEEE"
description = "Always `0`."

[[registers.status-register.fields]]
name = "0"
lsb = 2
width = 1
color = "EEEEEE"
description = "Always `0`."

[[registers.status-register.fields]]
name = "LVIDEO"
lsb = 3
width = 1
description = "**Video output status latch**<br>**0**: No active pixel is being output (black)<br>**1**: An active pixel is being output (normal or bright pixel)"

[[registers.status-register.fields]]
name = "1"
lsb = 4
width = 1
color = "EEEEEE"
description = "Always `1`."

[[registers.status-register.fields]]
name = "1"
lsb = 5
width = 1
color = "EEEEEE"
description = "Always `1`."

[[registers.status-register.fields]]
name = "1"
lsb = 6
width = 1
color = "EEEEEE"
description = "Always `1`."

[[registers.status-register.fields]]
name = "1"
lsb = 7
width = 1
color = "EEEEEE"
description = "Always `1`."
