version: "0.2"
language: en

dictionaries:
  - project-words

dictionaryDefinitions:
  - name: project-words
    path: ./.github/cspell/project-words.txt
    addWords: true

ignorePaths:
  - book/**
  - .git/**
  - scripts/**
  - local/**
  - references/**
